# Generated by Django 3.2.4 on 2021-07-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.IntegerField(default='1'),
        ),
    ]
