# Generated by Django 3.2.4 on 2021-07-09 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20210709_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
    ]
